# Variable 'Agent.Name' was defined in the Variables tab
# Variable 'GITHUB_TOKEN' was defined in the Variables tab
variables:
- name: BuildParameters.solution
  value: '**\*.sln'
trigger:
  branches:
    include:
    - main
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@3
    displayName: Set Assembly Manifest Data
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.8
    inputs:
      versionSpec: 6.8
  - task: NuGetCommand@2
    displayName: NuGet restore
  - task: VSBuild@1
    displayName: Build solution
    inputs:
      solution: $(BuildParameters.solution)
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      msbuildArchitecture: x64
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      versioningScheme: byPrereleaseNumber
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 9e9b1343-d4ed-4c03-8790-baf36bff9571/9e98deba-af02-4884-a792-ea7e09c7ba57
  - task: PublishSymbols@2
    displayName: Publish symbols path
    continueOnError: True
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
      SymbolServerType: TeamServices
...
